config/routes.rb
Danielbearl::Application.routes.draw do
  get 'log_in' => 'user_sessions#new', as: 'log_in'
  get 'log_out' => 'user_sessions#destroy', as: 'log_out'
  get 'blog' => 'posts#index', as: 'blog'
  get 'home' => 'pages#index', as: 'home'
  get 'posts/staging' => 'posts#staging', as: 'posts/staging'

  root to: 'pages#index'

  resources :pages
  resources :posts
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get "/:slug", to: "pages#show", as: :slug
  get "/:slug/edit", to: "pages#edit", as: :edit_slug
  put "/:slug", to: "pages#update", as: :update_slug
  post "/:slug", to: "pages#destroy", as: :destroy_slug
end

app/models/page.rb
class Page < ActiveRecord::Base

  default_scope { order('priority ASC') }

  validates_uniqueness_of :name

  before_save :update_slug

  def update_slug
    self.slug = name.parameterize
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :body
  serialize :tags

  default_scope {order('created_at DESC, updated_at DESC')}

  def lead
    terminal = [299, self.body.length - 1].min

    if terminal == self.body.length - 1
      return_str = self.body
    else
      return_str = self.body[0..terminal] + "..."
    end

    return return_str
  end

  def tags_list
    unless self.tags.blank?
      self.tags.join(", ")
    end
  end

  def tags_list=(value)
    tag_names = value.split(/,\s+/)
    self.update_attribute(:tags, tag_names)
  end

  def self.tag_cloud(posts)
    tags = {}

    posts.each do |post|
      unless post.tags_list.blank?
        post.tags_list.split(/,\s+/).each do |tag|
          if tags.has_key? tag
            tags[tag] += 1
          else
            tags[tag] = 1
          end
        end
      end
    end

    if tags.length < 1
      tags["None"] = 1
    end

    return tags
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :require_user

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  expose(:pages)
  expose(:page_slugs) { Page.select(:slug).map(&:slug) }

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless current_user
      redirect_to :root, notice: "You must be logged in to do that."
      return false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :require_user, only: [:new, :update, :create, :destroy]

  expose(:pages)
  expose(:page, finder: :find_by_slug, finder_parameter: :slug, attributes: :page_params)
  expose(:page_slugs) { Page.select(:slug).map(&:slug) }
  expose(:posts)
  expose(:newest_post) { Post.where("draft = false").first }

  def show
    if page.is_a? NilClass
      redirect_to "/404.html"
    end
  end

  def create
    if page.save
      redirect_to slug_path(page.slug), notice: "Page successfully created."
    else
      render :new
    end
  end
  
  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      redirect_to slug_path(@page.slug), notice: "Page successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @page = Page.find(params[:id])
    if @page.destroy
      redirect_to :root, notice: "Page successfully deleted."
    else
      flash.now "Page not destroyed!"
    end
  end

  private

  def page_params
    params.require(:page).permit(:name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_user, only: [:new, :update, :create, :destroy, :staging]

  expose(:post, attributes: :post_params)
  expose(:posts)
  expose(:published_posts) {
    if params[:tags]
      Post.where("tags && ARRAY[?] AND draft = false", params[:tags]).paginate(page: params[:page], per_page: 10)
    else
      Post.where("draft = false").paginate(page: params[:page], per_page: 10)
    end
  }

  expose(:drafts) { Post.where("draft = true").paginate(page: params[:page], per_page:10) }

  def create
    if post.save
      redirect_to posts_path, notice: "Post successfully created."
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to posts_path, notice: "Post successfully updated."
    else
      render :edit
    end
  end

  def destroy
    post.destroy
    redirect_to posts_path, notice: "Post successfully deleted."
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :tags_list, :draft)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def create
    user = User.authenticate(params[:email], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: "Successfully logged in."
    else
      flash.now.alert = "Invalid email or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, notice: "Successfully logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user)
  expose(:created_user) { User.new(user_params) }

  def create
    if created_user.save
      redirect_to root_path, notice: "User successfully created."
    else
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)

    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end

  end

  def tag_cloud(tags, classes)
    max = tags.sort_by{|k,v| v}.last[1]

    tags.each do |tag, count|
      index = count.to_f / max * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

  private

  def active_link_to(text, path, options={})
    if /^#{url_for(path)}/ =~ request.path
      options[:class] = "#{options[:class]} active"
    end
    
    link_to text, path, options
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_aside.html.haml
%aside.aside-column.offset1.span3#aside-right
  %article.widget-tag-cloud.widget
    %header
      %h1 Tag Cloud
      %ul.tagcloud
        - tag_cloud(Post.tag_cloud(posts), %w{tagCloud-1 tagCloud-2 tagCloud-3 tagCloud-4 tagCloud-5}) do |name, css_class|
          %li{ class: "tagCloud-tag #{css_class}" }
            = link_to name, posts_path(tags: name)

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title Danielbearl
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %link{href: 'http://fonts.googleapis.com/css?family=Poiret+One|PT+Serif|Open+Sans:400,300', rel: 'stylesheet', type: 'text/css'}
    %link{href: "http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.8.0/styles/default.min.css", rel: 'stylesheet', type: 'text/css'}
    %script{src: "http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.8.0/highlight.min.js"}
    %script hljs.initHighlightingOnLoad();

  %body
    .container
      .masthead.clearfix
        = link_to image_tag("DanielBearlLogo.png", id: "logo", alt: "danielbearl.com"), :root
        %ul.nav.ww-nav.pull-right.hidden-phone#nav
          %li
            = active_link_to 'Home', '/home'
          - pages.each do |page|
            %li
              = active_link_to page.name, slug_path(page.slug)
          %li
            = active_link_to 'Blog', '/blog'
      %hr

      - [:notice, :error, :alert].each do |level|
        - unless flash[level].blank?
          %div{class: "alert alert-#{flash_class(level)}"}
            %a{ href: "#", class: "close", data: { dismiss: "alert" } } &times;
            = flash[level]

      - if current_user
        = link_to "Log Out", "/log_out"

      = yield

      %hr
      .row.triple-row
        .span4.triple#triple-first
        .span4.triple#triple-second
          .zone.zone-triple-second
            %article.widget-triple-third.widget-html-widget.widget
              %header
                %h1 Connect
              = link_to raw('<i class="smicon-twitter"></i>'), "http://www.twitter.com/danbearl"
              = link_to raw('<i class="smicon-google"></i>'), "https://plus.google.com/116426476281213679784/"
              = link_to raw('<i class="smicon-github"></i>'), "http://www.github.com/danbearl"
      %hr
      .row
        .copyright.span12
          &copy;2013 Daniel Bearl

app/views/pages/_form.html.haml
- if page.errors.any?
  %ul
    - page.errors.full_messages.each do |error|
      %li.error= error

= f.label :name
= f.text_field :name, width: "50"

= f.label :body
= f.text_area :body, class: "span8", rows: "9"

= f.label :priority
= f.number_field :priority, class: "pull-left"

%br

= f.submit

app/views/pages/edit.html.haml
.row
  .offset2.span8
    = form_for page do |f|
      %fieldset
        %legend Edit Page
        = render partial: "form", locals: { f: f }

app/views/pages/index.html.haml
.row.main-content
  .offset1.span6.zone-content
    %article
      %h1 Welcome to DanielBearl.com

    %hr
    - unless newest_post.nil?
      %article
        %h2 Latest Post:

      = render partial: 'posts/full_post', locals: { post: newest_post }

  = render 'layouts/aside'

app/views/pages/new.html.haml
.row
  .offset2.span8
    = form_for page do |f|
      %fieldset
        %legend New Page
        = render partial: "form", locals: { f: f }

app/views/pages/show.html.haml
.row
  .span12
    %h1= page.name
- if current_user
  .row
    .span12
      %p
        = link_to "Edit", edit_slug_path(page.slug), class: "btn btn-mini"
        |
        = link_to "Delete", page_path(page), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-mini"
.row
  .span12
    %article
      :markdown
        #{page.body}

app/views/posts/_form.html.haml
= form_for post, class: "form-horizontal" do |f|
  %fieldset
    = f.label :title
    = f.text_field :title

    = f.label :body
    = f.text_area :body, rows: "10"

    = f.label :tags_list, "Tags"
    = f.text_field :tags_list

    .control-group
      = f.label :draft, class: "text-centered"
      .controls
        = f.check_box :draft

    = f.submit

app/views/posts/_full_post.html.haml
%article{ class: "blog-post" }
  .published
    = post.created_at
  %h1= post.title
  %div
    :markdown
      #{post.body}

app/views/posts/edit.html.haml
.row.main-content
  .offset3.span6
    %h1 Edit Post
    = render partial: "form"

app/views/posts/index.html.haml
.row.main-content
  .offset1.span6.zone-content
    - if current_user
      %div
        = link_to 'New Post', new_post_path, class: "button-link"
    %ul.blog-posts
      - posts.each do |post|
        - @position = ''
        - if posts.first == post then @position = "first" end
        - if posts.last == post then @position = "last" end
        %li{ class: @position }
          %article{ class: "blog-post" }
            .published
              = post.created_at
            %h1= post.title
            %div
              :markdown
                #{post.lead}
            - if post.lead.length < post.body.length
              = link_to "Read more...", post
            - unless post.tags.blank?
              %p.tags
                %span Tags:
                - post.tags_list.split(", ").each do |txt|
                  = link_to txt, posts_path(tags: txt)
            - if current_user
              = link_to 'Edit', edit_post_path(post), class: "button-link"
              = link_to 'Delete', post, method: :delete, data: { confirm: "Are you sure?" }, class: "button-link"
      = will_paginate posts

  = render 'layouts/aside'

app/views/posts/new.html.haml
.row.main-content
  .offset3.span6
    %h1 New Post
    = render partial: "form"

app/views/posts/show.html.haml
.row.main-content
  .offset2.span8.zone-content
    = render "full_post"

app/views/posts/staging.html.haml
.row.main-content
  .offset1.span6.zone-content
    - if current_user
      %div
        = link_to 'New Post', new_post_path, class: "button-link"
    %ul.blog-posts
      - drafts.each do |post|
        - @position = ''
        - if drafts.first == post then @position = "first" end
        - if drafts.last == post then @position = "last" end
        %li{ class: @position }
          %article{ class: "blog-post" }
            .published
              = post.created_at
            %h1= post.title
            %div
              :markdown
                #{post.lead}
            - if post.lead.length < post.body.length
              = link_to "Read more...", post
            - unless post.tags.blank?
              %p.tags
                %span Tags:
                - post.tags_list.split(", ").each do |txt|
                  = link_to txt, posts_path(tags: txt)
            - if current_user
              = link_to 'Edit', edit_post_path(post), class: "button-link"
              = link_to 'Delete', post, method: :delete, data: { confirm: "Are you sure?" }, class: "button-link"
      = will_paginate drafts

  = render 'layouts/aside'

app/views/user_sessions/new.html.haml
%h1 Sign In
= form_tag user_sessions_path do
  .field
    = label_tag :email
    %br
    = text_field_tag :email, params[:email]

  .field
    = label_tag :password
    %br
    = password_field_tag :password

  .action
    = submit_tag "Log In"